obj-$(CONFIG_PANEL_GENERIC) += panel-generic.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_SHARP_LQ043T1DG01) += panel-sharp-lq043t1dg01.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o

obj-$(CONFIG_PANEL_AT043TN13) += panel-at043tn13.o
obj-$(CONFIG_PANEL_AT070TN13) += panel-at070tn13.o
